[tools]
ruby = "3.4.3"
yarn = "1.22.22"
node = "22.20.0"
# php = "8.1.3"
# elixir = "1.11"
# erlang = "23.2"
go = "1.17"
# python = "3.11.1"
python = "3.10.0"
lua = "5.4.2"
postgres = "17.5"
rust = "1.88.0"
# perl = "5.34.0"
java = "openjdk-17.0.1"
julia = "1.10.4"
dart = "3.7.2"
flutter = "3.29.0"
# neovim = "stable"
neovim = "0.11.2"
